Activate poetry env since v2

diff --git a/.bashrc.d/python b/.bashrc.d/python
--- a/.bashrc.d/python
+++ b/.bashrc.d/python
@@ -11,5 +11,16 @@ function python-venv {
 }
 
 function activate {
-  source .venv/bin/activate
+  if test -f poetry.lock; then
+    if ! which -s poetry; then
+      echo '`poetry` not found'
+    else
+      path=$(poetry env activate | awk '{print $2}')
+      source "$path"
+    fi
+  elif test -f .venv/bin/activate; then
+    source .venv/bin/activate
+  else
+    echo "I don't know what you want me to activate..."
+  fi
 }
